### ISSUE TITLE
Non expected error executing a known command

### ISSUE THREAD

**Issue by darmng** [rofirrim/pingo#25]
In a private message, a non expected error:

```
Dani Armengol, [01.02.18 00:09]
/tapeta

PinchitoBot, [01.02.18 00:09]
I don't know what you mean with '/tapeta' Check the list of commands by typing '/' and disable your keyboard's auto-correct system
```
Nevertheless, command is executed correctly (a random log is shown in #pinchito).

**Comment by rofirrim** [comment]
Looks like the bug is in the bot itself rather than the web page. Mind to raise an issue to the bot project?

Thanks!
